// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "provider": string;
      "openaiBaseUrl": string;
      "openaiModel": string;
      "openaiReasoningEffort": string;
      "openaiEndpointHints": string;
      "webSearchEnabled": boolean;
      "webSearchProvider": string;
      "webSearchBaseUrl": string;
      "pdfToolsEnabled": boolean;
      "pdfToolsAutoApply": boolean;
      "agentConversationStore": string;
      "customContextStore": string;
    };
  }
}
